name: Deploy to Railway

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --release

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service c04bdb
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
